### ISSUE TITLE
Do you have any idea on SLOW/FAST mode switch?

### ISSUE THREAD

**Issue by cbwang2016** [SMerrony/tello-desktop#2]
It's hard to figure out this protocol using reverse-engineering

**Comment by cbwang2016** [comment]
I browsed your forked version of Gobot, it seems that you're working on reverse-engineering

**Comment by SMerrony** [comment]
There are a couple of commands that _might_ do it, and a lot of gaps in the command list which could be tried if you were feeling brave!

As I'm testing indoors at the moment it's not the top of my todo list.

Email me if you want to discuss.

**Comment by cbwang2016** [comment]
How do you test the commands? Do you use your phone to control and use Wireshark to view the packets, or just try all the commands in com.ryzerobotics.tello.gcs.core.cmd.d class one by one?
